### ISSUE TITLE
Problems with killing nodes

### ISSUE THREAD

**Issue by XmiliaH** [SeaOfNodes/Simple#12]
There seem to be multiple issues with killing nodes.

In some cases nodes that are still referenced from variables can be killed since the variable reference does not increase the nodes use count. The following script shows this issue where the add node referenced from `a` is killed when `b` is assinged one since the use count is zero.
```c
int a=arg+1; int b=a; b=1; return a+2;
```
This issue also happens when self assigning `a=a`.

The second issue might not be an issue but I was wondering why in https://github.com/SeaOfNodes/Simple/blob/10ed01188f78e3fad4b257a0241f9a89e2fdb405/chapter04/src/main/java/com/seaofnodes/simple/node/Node.java#L165 the node is checked with `isDead` and then killed again instead of a check with `isUnused` and then killed.

**Comment by cliffclick** [comment]
Bug is using HashMaps instead of ScopeNodes; the HashMap doesn't bump the use-count, so after `b=1` the prior def for `b`, which is `a` goes unused, gets nuked, but its still in the HashMap and technically live.

**Comment by dibyendumajumdar** [comment]
Hey @XmiliaH good to see you here and many thanks for the bug report

**Comment by XmiliaH** [comment]
Thank you two for working this series. I quite like watching CCC and though this will not teach me much I hope it will help future compiler developers.
