### ISSUE TITLE
Programs need to end with return

### ISSUE THREAD

**Issue by XmiliaH** [SeaOfNodes/Simple#19]
Currently programs need to end with a `return` statement. If it ends with a dfferent statement a cast exception occures as the `parse` method casts the last statement to `com.seaofnodes.simple.node.ReturnNode`.

Should this be included into the grammar or should `parse` return any statement node?

If the grammar is changed then the question would be about an `if` statement where both sides have an `return` statement.

```c
if (arg==1) {
    return 1;
} else {
    return 2;
}
```

**Comment by cliffclick** [comment]
@XmiliaH You've made several spot-comments, for which I thank you.
I run a Discord server for compiler geeks, Coffee Compiler Club, and a YouTube channel 
  https://www.youtube.com/@compilers 
with weekly chats about compilers with a dozen+ compiler writers.
If you want a Discord invite, email me cliffc@acm.org requesting.
We're always looking for more compiler gear-heads!
Thanks,
Cliff

**Comment by XmiliaH** [comment]
Just wrote you a mail about the Discotd invite.

**Comment by dibyendumajumdar** [comment]
> Currently programs need to end with a `return` statement. If it ends with a dfferent statement a cast exception occures as the `parse` method casts the last statement to `com.seaofnodes.simple.node.ReturnNode`.
> 
> Should this be included into the grammar or should `parse` return any statement node?
> 
> If the grammar is changed then the question would be about an `if` statement where both sides have an `return` statement.
> 
> ```c
> if (arg==1) {
>     return 1;
> } else {
>     return 2;
> }
> ```

The multiple return is part of this chapter, not done yet.

I think we expect a return node at the end even if there is no return statement - do you agree @cliffclick  ?

**Comment by cliffclick** [comment]
Closed, fixed in current PR #16.

**Comment by cliffclick** [comment]
Closed, fixed in current PR https://github.com/SeaOfNodes/Simple/pull/16.
