### ISSUE TITLE
Div node semantics

### ISSUE THREAD

**Issue by XmiliaH** [SeaOfNodes/Simple#20]
Currently the semantics of the div node are a bit unclear.
One the one hand it will throw in `compute` if the right hand side is zero, but on the other hand it does not have side effects.
As adding nodes with side effects should not happen in chapter 2, I think the div node should either be introduced later on or dividing by zero should be defined somehow.

**Comment by cliffclick** [comment]
I propose div-by-0 is 0.  Easy enough to code for & removes the runtime exception

**Comment by XmiliaH** [comment]
Fixed in https://github.com/SeaOfNodes/Simple/pull/16.
