### ISSUE TITLE
Communication channels?

### ISSUE THREAD

**Issue by melkyades** [SeaOfNodes/Simple#43]
Hi! I'm closely following the evolution of this repo, thanks for creating it. Is there any communication channel to ask questions?

**Comment by dibyendumajumdar** [comment]
Yes hi - there is a discord channel for compiler enthusiasts. Please contact @cliffclick

**Comment by cliffclick** [comment]
Or cliffc@acm.org - i need an email to shoot you a discord invite

**Comment by cliffclick** [comment]
Closing - send me email & we'll pick this up on discord
